### ISSUE TITLE
How to dynamically change the reciever_id for comments notification

### ISSUE THREAD

**Issue by Klashe** [Klashe/bookapp#1]
I'm using https://github.com/rails-engine/notifications. I used it for a threaded comment system in my web app like so.

comment.rb
```
belongs_to :commentable, polymorphic: true
belongs_to :user
belongs_to :parent, class_name: 'Comment', optional: true
has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

after_commit :notify_comment_created, on: [:create]
  def notify_comment_created
    return if self.commentable.blank?
    receiver_id = self.commentable&.user_id

    Notification.create(
      notify_type: "comment",
      target: self,
      second_target: self.commentable,
      actor_id: self.user_id,
      user_id: receiver_id
    )
  end
```
in views/notifications/_comment.html.erb
```
<% if notification.target %>
  <% if notification.second_target.is_a?(Article) %>
    <% if (notification.target.parent.present?) %>
      <div class=''>
        <p class="notifications-p"><i class="fa fa-comment text-secondary"></i> <b><%= link_to notification.actor.username, main_app.profile_path(notification.actor.username), class: "dark-link" %></b> replied to your comment on your <b><%= notification.second_target.class.name %>:</b> <b><%= link_to notification.second_target.title, main_app.article_path(notification.second_target), class: "dark-link" %></b></p>
      </div>

      <div class=''>
        <p class="notifications-p"><i><%= truncate(notification.target.content, length: 100) %></i></p>
      </div>
    <% else %>
      <div class=''>
        <p class="notifications-p"><i class="fa fa-comment text-secondary"></i> <b><%= link_to notification.actor.username, main_app.profile_path(notification.actor.username), class: "dark-link" %></b> commented on your <b><%= notification.second_target.class.name %>:</b> <b><%= link_to notification.second_target.title, main_app.article_path(notification.second_target), class: "dark-link" %></b></p>
      </div>

      <div class=''>
        <p class="notifications-p"><i><%= truncate(notification.target.content, length: 100) %></i></p>
      </div>
    <% end %>
<% end %>
```

What I want to do is to change the reciever_id dynamically so that if notification.target.parent is present, the comment.parent.user should receive the notification as a reply to his/her comment instead of the default notification which will be received by notification.target: self.

If you need more clarification about this issue, please let me know. Thanks!

**Comment by sammyhenningsson** [comment]
I'm not sure I fully understand, but why can't you just add that if statement when you create the notification?
```ruby
def notify_comment_created
    return if commentable.blank?
    if parent.present?
      receiver_id = parent.user_id
    else
      receiver_id = commentable.user_id
    end
...
```

**Comment by uzorjchibuzor** [comment]
> I'm not sure I fully understand, but why can't you just add that if statement when you create the notification?
> 
> ```ruby
> def notify_comment_created
>     return if commentable.blank?
>     if parent.present?
>       receiver_id = parent.user_id
>     else
>       receiver_id = commentable.user_id
>     end
> ...
> ```

I am not sure I fully understand either but I am certain with a few tweaks, your suggestion will work.

**Comment by Klashe** [comment]
Thanks for this... Yes it worked. Do you by any chance know how I can
attach the comment_id to the notification link so that when whenever the
link is clicked, it will navigate directly to the comment on the comment
section of the page.

**Comment by tumes** [comment]
Typically for that sort of "scroll to a thing" navigation, you can just rely on the fact that the browser will automatically scroll to a tag with an id that shows up in the url after the pound sign. For example, https://guides.rubyonrails.org/active_record_migrations.html#creating-a-migration auto scrolls to the section about creating a migration because that section header has the id `creating-a-migration`. Here's a relevant screenshot of the source:

<img width="549" alt="Screen Shot 2019-06-19 at 4 24 59 PM" src="https://user-images.githubusercontent.com/491145/59805522-ce066080-92ae-11e9-8aa2-cf4daba841d1.png">

So if you wrap the comment in a div with that comment id set, you should be good if you just append the id to the link with a pound sign.

**Comment by Klashe** [comment]
@tumes
Thanks or your suggestion. What about a situation where I have this as my normal comment partial
```
<li id="comment_<%= comment.id %>" class="comment">
  <div class="comment-content">
    <p class="notifications-p"><%= comment.content %></p>
  </div>
  <div class="comment-info">
    <small>-
      <%= link_to comment_user_avatar_select(comment), profile_path(comment.user.username) %>
      <%= link_to comment.user.username, profile_path(comment.user.username) %> &bull;
      <%= localize(comment.created_at, format: :long) %> &bull;
      <%= link_to "Edit", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link', remote: true  %> &bull;
      <%= link_to "Destroy", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Are your sure?"}, remote: true %> &bull;
      <%= link_to "Reply", polymorphic_path([:reply, comment.commentable, comment]), class: 'reply-comment-link', remote: true  %>
    </small>
  </div>
  <% if comment.replies.any? %>
    <ul>
      <%= render comment.replies %>
    </ul>
  <% end %>
</li>
```

**Comment by sammyhenningsson** [comment]
Yes, as @tumes wrote, it seems as passing in an anchor might work. So something like this might work.
```ruby
article_path(notification.second_target, anchor: "comment_#{notification.target.id}")
```
