### ISSUE TITLE
Conditional "Add to contacts" "Contact Pending" "Remove from contacts" on profile page

### ISSUE THREAD

**Issue by Klashe** [Klashe/bookapp#3]
The only way to add users to contact is through the conversations window where it checks if the user is added or not https://github.com/Klashe/bookapp/blob/master/app/views/private/conversations/conversation/heading/_add_user_to_contacts.html.erb

**Comment by Quarks0** [comment]
Just a heads up, it's nice to have links to the relevant controllers/views/models.
In this case it would be profiles controller, profile show, as well as the link you already provided.

- profiles_controller#show needs to fetch the Contact record and make it available in the view. I haven't checked the dbschema/models, but it seems to me that Contact has a contact_id and user_id. Note that current_user.id and @user.id could be in either field, so you'll have to use a where statement to check `"(contact_id = :current_user_id AND user_id = :user_id) OR (contact_id = :user_id AND user_id = :current_user_id)"`. See https://apidock.com/rails/ActiveRecord/QueryMethods/where just above the hash header
- profiles_show.html.erb should have an if/else block with 3 cases, based on the Contact record you fetch in the step above. Can you work out what those 3 cases will be? The link/button will have a different action depending on those scenarios

**Comment by Klashe** [comment]
Hi there. I started working on this issue and I think I'm making progress. I created contact helpers in the profile_helpers https://github.com/Klashe/bookapp/blob/b7742bf4cff313842879315659b0cbb4a9359430/app/helpers/profiles_helper.rb#L7 , added the contact views in profiles#show https://github.com/Klashe/bookapp/blob/b7742bf4cff313842879315659b0cbb4a9359430/app/views/profiles/_show_meta.html.erb#L51 and finally in the profiles#show controller https://github.com/Klashe/bookapp/blob/282bbd9051cd5813e98bea1c28abfc99a4b4238f/app/controllers/profiles_controller.rb#L10 but i'm getting this error, I think I'm not writing it correctly in the controller

```
undefined local variable or method `contact' for #<#<Class:0x0000000026a7e100>:0x0000000026a74970> Did you mean? @contact
```
but I only get this error when I'm on a user's page who is not on my contacts list

**Comment by Klashe** [comment]
Hi @Quarks0 . I started working on this issue and I think I'm making progress. I created contact helpers in the profile_helpers https://github.com/Klashe/bookapp/blob/b7742bf4cff313842879315659b0cbb4a9359430/app/helpers/profiles_helper.rb#L7 , added the contact views in profiles#show https://github.com/Klashe/bookapp/blob/b7742bf4cff313842879315659b0cbb4a9359430/app/views/profiles/_show_meta.html.erb#L51 and finally in the profiles#show controller https://github.com/Klashe/bookapp/blob/282bbd9051cd5813e98bea1c28abfc99a4b4238f/app/controllers/profiles_controller.rb#L10 but i'm getting this error, I think I'm not writing it correctly in the controller

```
undefined local variable or method `contact' for #<#<Class:0x0000000026a7e100>:0x0000000026a74970> Did you mean? @contact
```
but I only get this error when I'm on a user's page who is not on my contacts list

**Comment by Quarks0** [comment]
You made a typo in the show_meta view, just as the error says

**Comment by Klashe** [comment]
Thank @Quarks0 . I got it fixed... Thanks for tips, you should be a code teacher 😄
