### ISSUE TITLE
Adding an averge review filter fot books.

### ISSUE THREAD

**Issue by Klashe** [Klashe/bookapp#4]
I added the ability for users to leave a review on books. The review table has rating (:integer) and (:comment) columns and it's rendering well just as I want but I'm also trying to take things a little bit further  by making it possible to filter books based on the average review rating a book has. Since the review is a 1-5 integer represented by stars.

Example: 
I want something like

FILTER BOOKS BY AVERAGE REVIEW RATING
⭐️⭐️⭐️⭐️⭐️ (link_to the book_path with average rating of 5)
⭐️⭐️⭐️⭐️
⭐️⭐️⭐️
⭐️⭐️
⭐️ 

https://github.com/Klashe/bookapp/blob/11ee8e475696480c770e725f39ae93943b2df80e/app/controllers/books_controller.rb#L39

I also want to be able to display average review on books index action too, currently it only shows on show action.

**Comment by Quarks0** [comment]
Just going to cover high level design here, but I would argue it's good practice to know how you want/should be building these solutions, not relying too heavily on what others tell you to do

You're on the right track - you want a review table with the user and book. If you want the average review when displaying books, you'll have to fetch the book's ratings in the index method. Active record has a .includes method that you should look into. One thing to consider is that calculating the average rating per book can get really slow - you may want an average rating record as well.
